Don't threat warnings as errors
Don't threat warnings as errors. This breaks compilation with Erlang 20
because of gen_fsm deprecation:

...
src/riak_core_vnode_manager.erl:469: gen_fsm:send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
src/riak_core_vnode_manager.erl:473: gen_fsm:send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
Compiling src/riak_core_vnode_manager.erl failed:
DEBUG: Worker compilation failed: {{error,
                                    {error,[],
                                     [["src/riak_core_vnode_manager.erl:469: gen_fsm:send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2\n",
                                       "src/riak_core_vnode_manager.erl:473: gen_fsm:send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2\n"]]}},
                                   {source,"src/riak_core_vnode_manager.erl"}}
ERROR: compile failed while processing /builddir/build/BUILD/riak_core-2.1.10: rebar_abort
...

Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>